// WrtPilot - nftables ruleset generator.
//
// generate() is a pure function: model in, nft script out. The script is
// idempotent - it can be loaded repeatedly (by `wrtpilot apply` and by fw4,
// which includes it from /usr/share/nftables.d/ruleset-post/) without
// losing the state that lives in the kernel: per-IP traffic counters and the
// IP sets dnsmasq fills for domain blocklists. Everything else (chains,
// MAC sets, schedule windows) is flushed and rebuilt from UCI each time.

'use strict';

import { VERSION } from 'wrtpilot.util';

export const TABLE = 'wrtpilot';
export const ACCT_TABLE = 'wrtpilot_acct';

// Well-known DNS-over-HTTPS / DoT resolver addresses. Filtered devices may
// not reach them on 443/853 so they cannot bypass the group DNS.
export const DOH_V4 = [
	'1.1.1.1', '1.0.0.1', '1.1.1.2', '1.0.0.2',
	'8.8.8.8', '8.8.4.4',
	'9.9.9.9', '149.112.112.112', '9.9.9.10', '149.112.112.10', '9.9.9.11', '149.112.112.11',
	'208.67.222.222', '208.67.220.220',
	'94.140.14.14', '94.140.15.15',
	'45.90.28.0/24', '45.90.30.0/24',
	'76.76.2.0/24', '76.76.10.0/24',
	'194.242.2.0/24',
	'185.222.222.222', '45.11.45.11',
	'101.101.101.101'
];

export const DOH_V6 = [
	'2606:4700:4700::1111', '2606:4700:4700::1001',
	'2606:4700:4700::1112', '2606:4700:4700::1002',
	'2001:4860:4860::8888', '2001:4860:4860::8844',
	'2620:fe::fe', '2620:fe::9', '2620:fe::11', '2620:fe::fe:11',
	'2620:119:35::35', '2620:119:53::53',
	'2a10:50c0::ad1:ff', '2a10:50c0::ad2:ff',
	'2a07:a8c0::/33', '2a07:a8c1::/33',
	'2a09::', '2a11::'
];

function q(s) {
	return `"${s}"`;
}

function ifset(devs) {
	return '{ ' + join(', ', map(devs, q)) + ' }';
}

function elems(list) {
	return '{ ' + join(', ', list) + ' }';
}

function chunked_add(out, set, items) {
	// keep individual statements short for older nft parsers
	for (let i = 0; i < length(items); i += 64)
		push(out, `add element inet ${TABLE} ${set} ${elems(slice(items, i, i + 64))}`);
}

export function group_set(gid, kind) {
	return `g_${gid}_${kind}`;
};

// Names of the sets generate() declares for the given model.
export function desired_sets(model) {
	let sets = [ 'blocked_mac', 'filtered_mac', 'doh4', 'doh6', 'dohdyn4', 'dohdyn6' ];

	for (let g in model.groups) {
		push(sets, group_set(g.id, 'mac'));

		if (g.windows)
			push(sets, group_set(g.id, 'win'));

		if (g.blocklist)
			push(sets, group_set(g.id, 'bl4'), group_set(g.id, 'bl6'));
	}

	return sets;
};

export function desired_chains() {
	return [ 'forward', 'dstnat', 'wp_reject' ];
};

// model:
//   lan:      [ "br-lan", ... ]
//   blocked:  [ { mac, until } ]          internet blocks (until 0 = permanent)
//   paused:   [ { macs: [], until } ]     until -1 = indefinite
//   quota:    [ { mac, until } ]          quota exceeded, blocked until midnight
//   groups:   [ { id, macs, windows, blocklist, dns_port, filtered } ]
//   coarse:   [ { mac, ips4, ips6, dl_kbps, ul_kbps } ]  policing fallback
export function generate(model) {
	let lan = ifset(model.lan);
	let from_lan = `iifname ${lan} oifname != ${lan}`;
	let to_lan = `oifname ${lan} iifname != ${lan}`;
	let out = [];
	let groups = filter(model.groups ?? [], g => length(g.macs) > 0);

	push(out,
		`# Generated by WrtPilot ${VERSION} - do not edit, run "wrtpilot apply" instead.`,
		'',
		'# --- traffic accounting (counters survive reloads) ---',
		`table inet ${ACCT_TABLE} {`,
		'\tset dl4 { type ipv4_addr; size 65535; flags dynamic,timeout; timeout 1h; counter; }',
		'\tset dl6 { type ipv6_addr; size 65535; flags dynamic,timeout; timeout 1h; counter; }',
		'\tset ul4 { type ipv4_addr; size 65535; flags dynamic,timeout; timeout 1h; counter; }',
		'\tset ul6 { type ipv6_addr; size 65535; flags dynamic,timeout; timeout 1h; counter; }',
		'\tchain forward { type filter hook forward priority filter - 10; policy accept; }',
		'}',
		`flush chain inet ${ACCT_TABLE} forward`,
		`table inet ${ACCT_TABLE} {`,
		'\tchain forward {',
		`\t\t${to_lan} update @dl4 { ip daddr }`,
		`\t\t${to_lan} update @dl6 { ip6 daddr }`,
		`\t\t${from_lan} update @ul4 { ip saddr }`,
		`\t\t${from_lan} update @ul6 { ip6 saddr }`,
		'\t}',
		'}',
		'',
		'# --- access control ---',
		`table inet ${TABLE} {`,
		'\tset blocked_mac { type ether_addr; }',
		'\tset filtered_mac { type ether_addr; }',
		'\tset doh4 { type ipv4_addr; flags interval; }',
		'\tset doh6 { type ipv6_addr; flags interval; }',
		'\tset dohdyn4 { type ipv4_addr; size 65535; flags timeout; timeout 1d; }',
		'\tset dohdyn6 { type ipv6_addr; size 65535; flags timeout; timeout 1d; }'
	);

	for (let g in groups) {
		push(out, `\tset ${group_set(g.id, 'mac')} { type ether_addr; }`);

		if (g.windows)
			push(out, `\tset ${group_set(g.id, 'win')} { typeof meta time; flags interval; }`);

		if (g.blocklist)
			push(out,
				`\tset ${group_set(g.id, 'bl4')} { type ipv4_addr; size 65535; flags timeout; timeout 6h; }`,
				`\tset ${group_set(g.id, 'bl6')} { type ipv6_addr; size 65535; flags timeout; timeout 6h; }`);
	}

	push(out,
		'\tchain wp_reject { }',
		'\tchain forward { type filter hook forward priority filter - 5; policy accept; }',
		'\tchain dstnat { type nat hook prerouting priority dstnat - 5; policy accept; }',
		'}');

	for (let c in desired_chains())
		push(out, `flush chain inet ${TABLE} ${c}`);

	for (let s in [ 'blocked_mac', 'filtered_mac', 'doh4', 'doh6' ])
		push(out, `flush set inet ${TABLE} ${s}`);

	for (let g in groups) {
		push(out, `flush set inet ${TABLE} ${group_set(g.id, 'mac')}`);

		if (g.windows)
			push(out, `flush set inet ${TABLE} ${group_set(g.id, 'win')}`);
	}

	// --- rules ---
	let fwd = [];

	for (let b in model.blocked ?? [])
		if (b.until > 0)
			push(fwd, `${from_lan} ether saddr ${b.mac} meta time < ${b.until} goto wp_reject`);

	if (length(filter(model.blocked ?? [], b => b.until == 0)))
		push(fwd, `${from_lan} ether saddr @blocked_mac goto wp_reject`);

	for (let p in model.paused ?? []) {
		if (!length(p.macs))
			continue;

		let cond = (p.until > 0) ? ` meta time < ${p.until}` : '';

		push(fwd, `${from_lan} ether saddr ${elems(p.macs)}${cond} goto wp_reject`);
	}

	for (let b in model.quota ?? [])
		push(fwd, `${from_lan} ether saddr ${b.mac} meta time < ${b.until} goto wp_reject`);

	let any_filtered = false;

	for (let g in groups) {
		let macset = '@' + group_set(g.id, 'mac');

		if (g.windows)
			push(fwd, `${from_lan} ether saddr ${macset} meta time != @${group_set(g.id, 'win')} goto wp_reject`);

		if (g.blocklist) {
			push(fwd, `${from_lan} ether saddr ${macset} ip daddr @${group_set(g.id, 'bl4')} goto wp_reject`);
			push(fwd, `${from_lan} ether saddr ${macset} ip6 daddr @${group_set(g.id, 'bl6')} goto wp_reject`);
		}

		if (g.filtered)
			any_filtered = true;
	}

	if (any_filtered) {
		// stop DNS-over-TLS / DNS-over-HTTPS bypass of the group resolver
		push(fwd,
			`iifname ${lan} ether saddr @filtered_mac meta l4proto { tcp, udp } th dport 853 goto wp_reject`,
			`iifname ${lan} ether saddr @filtered_mac meta l4proto { tcp, udp } th dport 443 ip daddr @doh4 goto wp_reject`,
			`iifname ${lan} ether saddr @filtered_mac meta l4proto { tcp, udp } th dport 443 ip6 daddr @doh6 goto wp_reject`,
			`iifname ${lan} ether saddr @filtered_mac meta l4proto { tcp, udp } th dport 443 ip daddr @dohdyn4 goto wp_reject`,
			`iifname ${lan} ether saddr @filtered_mac meta l4proto { tcp, udp } th dport 443 ip6 daddr @dohdyn6 goto wp_reject`);
	}

	// policing fallback when tc/ifb shaping is unavailable
	for (let c in model.coarse ?? []) {
		if (c.ul_kbps > 0) {
			let rate = max(1, c.ul_kbps / 8);

			push(fwd, `${from_lan} ether saddr ${c.mac} limit rate over ${rate} kbytes/second burst ${max(16, rate / 4)} kbytes drop`);
		}

		if (c.dl_kbps > 0) {
			let rate = max(1, c.dl_kbps / 8);
			let lim = `limit rate over ${rate} kbytes/second burst ${max(16, rate / 4)} kbytes drop`;

			if (length(c.ips4))
				push(fwd, `${to_lan} ip daddr ${elems(c.ips4)} ${lim}`);

			if (length(c.ips6))
				push(fwd, `${to_lan} ip6 daddr ${elems(c.ips6)} ${lim}`);
		}
	}

	let nat = [];

	for (let g in groups)
		if (g.dns_port)
			push(nat, `iifname ${lan} ether saddr @${group_set(g.id, 'mac')} meta l4proto { tcp, udp } th dport 53 redirect to :${g.dns_port}`);

	push(out,
		`table inet ${TABLE} {`,
		'\tchain wp_reject {',
		'\t\tmeta l4proto tcp reject with tcp reset',
		'\t\treject with icmpx type admin-prohibited',
		'\t}',
		'\tchain forward {');

	for (let r in fwd)
		push(out, '\t\t' + r);

	push(out, '\t}', '\tchain dstnat {');

	for (let r in nat)
		push(out, '\t\t' + r);

	push(out, '\t}', '}');

	// --- set contents ---
	chunked_add(out, 'blocked_mac', map(filter(model.blocked ?? [], b => b.until == 0), b => b.mac));
	chunked_add(out, 'doh4', DOH_V4);
	chunked_add(out, 'doh6', DOH_V6);

	let filtered = [];

	for (let g in groups) {
		chunked_add(out, group_set(g.id, 'mac'), g.macs);

		if (g.windows)
			chunked_add(out, group_set(g.id, 'win'), map(g.windows, w => `${w[0]}-${w[1] - 1}`));

		if (g.filtered)
			push(filtered, ...g.macs);
	}

	chunked_add(out, 'filtered_mac', uniq(filtered));

	return join('\n', out) + '\n';
};

// Commands that remove sets left over from deleted groups. Must run after the
// generated script in the same transaction (rules referencing them are gone).
export function stale_cleanup(existing_sets, model) {
	let want = {};
	let out = [];

	for (let s in desired_sets({ groups: filter(model.groups ?? [], g => length(g.macs) > 0) }))
		want[s] = true;

	for (let s in existing_sets)
		if (!want[s])
			push(out, `delete set inet ${TABLE} ${s}`);

	return out;
};

export function teardown(existing_tables) {
	let out = [];

	for (let t in [ TABLE, ACCT_TABLE ])
		if (index(existing_tables, t) >= 0)
			push(out, `delete table inet ${t}`);

	return out;
};
